load data
 infile './DATOSPELEXTRA.csv'
 into table DATOSPELEXTRA
 fields terminated by ";"
 ( TITLE, PRODUCTION_YEAR, SERIE_TITLE, SERIE_PROD_YEAR, SEASON_NR,
    EPISODE_NR, SERIES_YEARS, KIND, TITLELINK, PRODUCTIONYEARLINK,
    LINK, KEYWORD, NAME, GENDER, PERSON_INFO, INFO_CONTEXT, ROLE,
    ROLE_NAME, NOTE, NR_ORDER )