--POBLAR PERSONA
CREATE VIEW NACIDOS AS 
    SELECT DISTINCT(NAME), TRANSLATE(
            TRIM(SUBSTR(PERSON_INFO, INSTR(PERSON_INFO, ',', -1) +1)),
            'x[]()','x')
            AS NACIMIENTO
    FROM DATOSDB.DATOSPELICULAS
    WHERE INFO_CONTEXT = 'birth notes';
    
INSERT INTO PERSONA (NOMBRE, NACIMIENTO, GENERO)
SELECT DISTINCT(P.NAME), N.NACIMIENTO, P.GENDER 
FROM DATOSPELICULAS P
FULL OUTER JOIN NACIDOS N ON P.NAME = N.NAME
WHERE P.GENDER IS NOT NULL;
DROP VIEW NACIDOS;

-- SQL PARA POBLAR OBRA CON PELICULAS
INSERT INTO OBRA (TITULO, AÑO_ESTRENO,TIPO)
SELECT TITLE, PRODUCTION_YEAR, 'P' TIPO
FROM DATOSDB.DATOSPELICULAS
WHERE KIND='movie'
GROUP BY TITLE,PRODUCTION_YEAR
ORDER BY TITLE;

-- SQL PARA POBLAR OBRA CON SERIES
INSERT INTO OBRA (TITULO, PERIODO_EMISION, TIPO)
SELECT TITLE, SERIES_YEARS, 'S' TIPO
FROM DATOSDB.DATOSPELICULAS
WHERE KIND='tv series'
GROUP BY TITLE, SERIES_YEARS
ORDER BY TITLE;

-- POBLAR GENERO
INSERT INTO GENERO (NOMBRE)
SELECT DISTINCT KEYWORD NOMBRE 
FROM DATOSDB.DATOSPELICULAS 
WHERE KEYWORD IS NOT NULL;

-- POBLAR CLASIFICAR
INSERT INTO CLASIFICAR (OBRA, GENERO)
WITH GENERO_PELI AS
        (SELECT D.TITLE TITULO, D.PRODUCTION_YEAR AÑO_PRODUCCION, D.KEYWORD GENERO,O.ID_OBRA OBRA
        FROM DATOSDB.DATOSPELICULAS D, OBRA O
        WHERE D.KIND='movie' AND
              D.KEYWORD IS NOT NULL AND
              O.TITULO = D.TITLE AND
              O.AÑO_ESTRENO = D.PRODUCTION_YEAR
        GROUP BY D.TITLE, D.PRODUCTION_YEAR, D.KEYWORD, O.ID_OBRA
        ORDER BY D.TITLE),
    GENERO_SERIE AS
        (SELECT D.TITLE TITULO, D.SERIES_YEARS PERIODO_EMISION, D.KEYWORD GENERO,O.ID_OBRA OBRA
        FROM DATOSDB.DATOSPELICULAS D, OBRA O
        WHERE D.KIND='tv series' AND
              D.KEYWORD IS NOT NULL AND
              O.TITULO = D.TITLE AND
              O.PERIODO_EMISION = D.SERIES_YEARS
        GROUP BY D.TITLE, D.SERIES_YEARS, D.KEYWORD, O.ID_OBRA
        ORDER BY D.TITLE)
SELECT OBRA, GENERO
FROM GENERO_PELI
UNION
SELECT OBRA, GENERO
FROM GENERO_SERIE;

