WITH GOLES_POR_JORNADA AS
    (
        SELECT TEMPORADA,JORNADA, SUM(GOLES_LOCAL) + SUM(GOLES_VISITANTE) GOLES_JORNADA
        FROM PARTIDO
        GROUP BY TEMPORADA,JORNADA
    )
SELECT g.TEMPORADA, g.JORNADA, g.GOLES_JORNADA
FROM GOLES_POR_JORNADA g
WHERE g.TEMPORADA>'20102011' AND
g.GOLES_JORNADA=(SELECT MAX(h.GOLES_JORNADA)
                       FROM GOLES_POR_JORNADA h
                       WHERE h.TEMPORADA=g.TEMPORADA
                       GROUP BY TEMPORADA)
ORDER BY TEMPORADA DESC;