SELECT g.TEMPORADA, g.JORNADA, g.GOLES_JORNADA
FROM GOLES_POR_JORNADA g
WHERE g.TEMPORADA>'20102011' AND
g.GOLES_JORNADA=(SELECT MAX(h.GOLES_JORNADA)
                       FROM GOLES_POR_JORNADA h
                       WHERE h.TEMPORADA=g.TEMPORADA
                       GROUP BY TEMPORADA)
ORDER BY TEMPORADA DESC;