--POBLAR PERSONA
CREATE VIEW NACIDOS AS 
    SELECT DISTINCT(NAME), TRIM(TRAILING ']' FROM
            TRIM(SUBSTR(PERSON_INFO, INSTR(PERSON_INFO, ',', -1) +1)))
            AS NACIMIENTO
    FROM DATOSPELICULAS
    WHERE INFO_CONTEXT = 'birth notes';
    
INSERT INTO PERSONA (NOMBRE, NACIMIENTO, GENERO)
SELECT DISTINCT(P.NAME), N.NACIMIENTO, P.GENDER 
FROM DATOSPELICULAS P
FULL OUTER JOIN NACIDOS N ON P.NAME = N.NAME
WHERE P.GENDER IS NOT NULL;
DROP VIEW NACIDOS;

-- SQL PARA POBLAR OBRA CON PELICULAS
INSERT INTO OBRA (TITULO, AÑO_ESTRENO,TIPO)
SELECT TITLE, PRODUCTION_YEAR, 'P' TIPO
FROM DATOSPELICULAS
WHERE KIND='movie'
GROUP BY TITLE,PRODUCTION_YEAR
ORDER BY TITLE;

-- SQL PARA POBLAR OBRA CON SERIES
INSERT INTO OBRA (TITULO, PERIODO_EMISION, TIPO)
SELECT TITLE, SERIES_YEARS, 'S' TIPO
FROM DATOSPELICULAS
WHERE KIND='tv series'
GROUP BY TITLE, SERIES_YEARS
ORDER BY TITLE;

--SQL PARA POBLAR OBRA CON PELICULAS Y SERIES A LA VEZ
CREATE OR REPLACE VIEW obras AS
WITH peliculas AS (
    SELECT DISTINCT title, production_year
    FROM DATOSDB.DATOSPELICULAS
    WHERE kind = 'movie'
),
series AS (
    SELECT DISTINCT title, series_years
    FROM DATOSDB.DATOSPELICULAS
    WHERE kind = 'tv series'
)
SELECT title, production_year, NULL AS series_years
FROM peliculas
UNION ALL
SELECT title, NULL AS production_year, series_years
FROM series;

INSERT INTO OBRA (TITULO, AÑO_ESTRENO, PERIODO_EMISION, TIPO)
SELECT DISTINCT V.title, V.production_year, V.series_years, 
                CASE
                    WHEN kind = 'movie' THEN 'P'
                    WHEN kind = 'tv series' THEN 'S'
                END AS TIPO
FROM obras V, datosdb.datospeliculas M
WHERE V.title = M.title AND ((V.production_year = M.production_year AND kind = 'movie') OR 
                            (V.series_years = M.series_years AND kind = 'tv series'));

-- POBLAR GENERO
INSERT INTO GENERO (NOMBRE)
SELECT DISTINCT KEYWORD NOMBRE 
FROM DATOSDB.DATOSPELICULAS 
WHERE KEYWORD IS NOT NULL;

-- POBLAR CLASIFICAR
INSERT INTO CLASIFICAR (OBRA, GENERO)
WITH GENERO_PELI AS
        (SELECT D.TITLE TITULO, D.PRODUCTION_YEAR AÑO_PRODUCCION, D.KEYWORD GENERO,O.ID_OBRA OBRA
        FROM DATOSDB.DATOSPELICULAS  D, OBRA O
        WHERE D.KIND='movie' AND
              D.KEYWORD IS NOT NULL AND
              O.TITULO = D.TITLE AND
              O.AÑO_ESTRENO = D.PRODUCTION_YEAR
        GROUP BY D.TITLE, D.PRODUCTION_YEAR, D.KEYWORD, O.ID_OBRA
        ORDER BY D.TITLE),
    GENERO_SERIE AS
        (SELECT D.TITLE TITULO, D.SERIES_YEARS PERIODO_EMISION, D.KEYWORD GENERO,O.ID_OBRA OBRA
        FROM DATOSDB.DATOSPELICULAS  D, OBRA O
        WHERE D.KIND='tv series' AND
              D.KEYWORD IS NOT NULL AND
              O.TITULO = D.TITLE AND
              O.PERIODO_EMISION = D.SERIES_YEARS
        GROUP BY D.TITLE, D.SERIES_YEARS, D.KEYWORD, O.ID_OBRA
        ORDER BY D.TITLE)
SELECT OBRA, GENERO
FROM GENERO_PELI
UNION
SELECT OBRA, GENERO
FROM GENERO_SERIE;

---CAPITULO
CREATE OR REPLACE VIEW capitulos AS (  --Saca los id_obra de la serie de cada capítulo
        SELECT distinct O.id_obra, M.title
        FROM OBRA O, DATOSDB.DATOSPELICULAS M
        WHERE O.titulo = M.serie_title
    );
INSERT INTO CAPITULO (n_cap, titulo_cap, temporada, mi_serie)
SELECT DISTINCT (M.episode_nr), M.title, M.season_nr, C.id_obra
FROM DATOSDB.DATOSPELICULAS M, CAPITULOS C, OBRA O
WHERE C.id_obra = O.id_obra AND M.title = C.title AND episode_nr IS NOT NULL
ORDER BY (id_obra);

